### PR TITLE
added to_s method on PactUri for printing out the uri when running the t...

### PR DESCRIPTION
**Pull request by lifeifei**
This is to fix the Issue #76

### CODE REVIEW

**Comment by bethesque** [comment]
Thanks!

**Comment by bethesque** [comment]
Do you think it would be a good idea to ***** out the password?

**Comment by lifeifei** [comment]
Yes, I think it's better to ***** out the password.  The failed test message will be displayed in the build console, which might be visible to everyone who has the read access.

**Comment by bethesque** [comment]
Thanks!

**Pull request merged**
